name = "ExplainabilityMethods"
uuid = "cd722a4f-8d55-446b-8550-a4aabc9151ab"
authors = ["Adrian Hill"]
version = "0.1.0"

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
ColorSchemes = "3"
Flux = "0.12"
ImageCore = "0.8, 0.9"
JLD2 = "0.4"
Metalhead = "0.6"
Zygote = "0.6"
julia = "1.6"

[extras]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Metalhead = "dbeba491-748d-5e0e-a39e-b530a07fa0cc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReferenceTests = "324d217c-45ce-50fc-942e-d289b448e8cf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["JLD2", "Metalhead", "Random", "ReferenceTests", "Test"]
