name = "ExplainableAI"
uuid = "4f1bc3e1-d60d-4ed0-9367-9bdff9846d3b"
authors = ["Adrian Hill <gh@adrianhill.de>"]
version = "0.6.3"

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"
XAIBase = "9b48221d-a747-4c1b-9860-46a1d8ba24a7"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[weakdeps]
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[extensions]
TullioLRPRulesExt = "Tullio"

[compat]
ColorSchemes = "3.18"
Distributions = "0.25"
Flux = "0.13, 0.14"
ImageCore = "0.9, 0.10"
ImageTransformations = "0.9, 0.10"
MacroTools = "0.5"
Reexport = "1"
Tullio = "0.3"
XAIBase = "1.1.1"
Zygote = "0.6"
julia = "1.6"
